"""empty message

Revision ID: 07213f4625d8
Revises: 741afbce0e5f
Create Date: 2025-11-30 19:03:38.624057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07213f4625d8'
down_revision = '741afbce0e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.alter_column('decrease_pct',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.alter_column('decrease_pct',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###
