"""empty message

Revision ID: 741afbce0e5f
Revises: 8e3195cc2c20
Create Date: 2025-11-29 23:46:15.542517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741afbce0e5f'
down_revision = '8e3195cc2c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
