"""empty message

Revision ID: 8e3195cc2c20
Revises: 
Create Date: 2025-11-29 15:19:30.728677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3195cc2c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_restaurant_company_name', ['company_id', 'name'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_category_restaurant_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_restaurant_id'), ['restaurant_id'], unique=False)
        batch_op.create_index('ix_category_restaurant_name', ['restaurant_id', 'name'], unique=False)

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product_api', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("unit IN ('g','kg','ml','l','ud')", name='ck_ingredient_unit_valid'),
    sa.CheckConstraint('price_per_unit >= 0', name='ck_ingredient_price_nonnegative'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_product_api'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_ingredient_restaurant_name')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index('ix_ingredient_restaurant_name', ['restaurant_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredients_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_dish_category_name')
    )
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.create_index('ix_dish_category_name', ['category_id', 'name'], unique=False)
        batch_op.create_index('ix_dish_restaurant', ['restaurant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dishes_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dishes_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('dish_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('gross_weight', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('decrease_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.CheckConstraint('decrease_pct >= 0 AND decrease_pct <= 100', name='ck_di_decrease_range'),
    sa.CheckConstraint('gross_weight >= 0', name='ck_di_weight_nonnegative'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'ingredient_id', name='uq_di_dish_ingredient')
    )
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.create_index('ix_di_dish_ing', ['dish_id', 'ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dish_ingredient_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dish_ingredient_ingredient_id'), ['ingredient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_ingredient_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_dish_ingredient_dish_id'))
        batch_op.drop_index('ix_di_dish_ing')

    op.drop_table('dish_ingredient')
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dishes_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_dishes_category_id'))
        batch_op.drop_index('ix_dish_restaurant')
        batch_op.drop_index('ix_dish_category_name')

    op.drop_table('dishes')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_restaurant_id'))
        batch_op.drop_index('ix_ingredient_restaurant_name')

    op.drop_table('ingredients')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_category_restaurant_name')
        batch_op.drop_index(batch_op.f('ix_categories_restaurant_id'))

    op.drop_table('categories')
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurant_company_name')
        batch_op.drop_index(batch_op.f('ix_restaurant_company_id'))

    op.drop_table('restaurant')
    op.drop_table('user')
    # ### end Alembic commands ###
